name: "Deploy to server"

on:
    push:
        branches: ["main"]

jobs:
    build_docker_image:
        runs-on: ubuntu-latest
        steps:
            - 
                uses: actions/checkout@v4
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            -
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
                name: Build and push
                uses: docker/build-push-action@v6
                with:
                    push: true
                    tags: adalave/evert-http:stable

    re-build-docker-image:
        needs: build_docker_image
        runs-on: ubuntu-latest
        steps:
            -  
                uses: appleboy/ssh-action@v1.0.3
                with:
                    host: ${{ secrets.DEV_HOST }}
                    username: ${{ secrets.DEV_USER }}
                    key: ${{ secrets.DEV_SSH }}
        
                    script: |
                        sudo docker stop evert-http
                        sudo docker container rm evert-http
                        sudo docker image rm adalave/evert-http:stable
                        docker pull adalave/evert-http:stable
                        docker run -p 8080:8080 -d --name evert-http adalave/evert-http:stable